#!/usr/bin/python

import os, subprocess, filecmp

files = open("./files.txt", "r", encoding="utf-8").read().split("\n")

for f in files:
    name = "./config/" + f.replace("/", "$")
    f = os.path.expanduser(f)
    if not os.path.exists(f):
        continue
    if filecmp.cmp(f, name):
        continue
    subprocess.call(
        ["code", "--wait", "-d", f, name],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
