[ids]

*

[main]

capslock = layer(meta)
muhenkan = layer(vim_layer)

[vim_layer]

i = kp1
o = muhenkan
h = left
j = down
k = up
l = right
n = A-left
m = A-right

[ = command(sudo -u '#1000' XDG_RUNTIME_DIR=/run/user/1000 pactl set-sink-volume 0 -2dB)
] = command(sudo -u '#1000' XDG_RUNTIME_DIR=/run/user/1000 pactl set-sink-volume 0 +2dB)
p = command(sudo -u '#1000' XDG_RUNTIME_DIR=/run/user/1000 pactl set-sink-mute 0 toggle)
