scrolling:
  multiplier: 10
cursor:
  style:
    shape: beam
shell:
  program: fish
key_bindings:
  - { key: Equals, mods: Control|Shift, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
